### ISSUE TITLE
Native image Unsupported GB2312 Charset Exception 

### ISSUE THREAD

**Issue by HuangDayu** [graalvm/native-build-tools#142]
Hello, I have encountered some problems.

The project can run normally in IDEA, but an exception is thrown when Native Image starts: java.nio.charset.UnsupportedCharsetException: GB2312

GraalVM Version ：

```shell
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b07)
OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 25.302-b07-jvmci-21.2-b08, mixed mode)
```

Source code :

```java
public class MessageManagerImpl implements MessageManager {
    private static final Charset GB2312_CHARSET = Charset.forName("GB2312");
    ....
}
```

Native Application Bulid :

```shell
native-image -cp application-shaded.jar -H:IncludeResourceBundles=javax.servlet.LocalStrings -H:IncludeResourceBundles=javax.servlet.http.LocalStrings -H:-CheckToolchain -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:+RemoveSaturatedTypeFlows --allow-incomplete-classpath --no-fallback --enable-all-security-services --enable-http --initialize-at-run-time=com.company.application -H:Name=native-application
```

Native application bulid success , but an exception is thrown when starts ：

```shell
Caused by: java.nio.charset.UnsupportedCharsetException: GB2312
        at java.nio.charset.Charset.forName(Charset.java:531) ~[na:na]
        at com.company.application.MessageManagerImpl .<clinit>(MessageManagerImpl .java:26) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295) ~[na:na]
        ... 37 common frames omitted
```

How can I solve this problem ? Thanks ！

**Comment by HuangDayu** [comment]
我已经解决了此问题。

I have solved this problem. 

```java
private static final Charset GB2312_CHARSET = new GB18030();
```

**Comment by wangliang181230** [comment]
The same problem: `Charset.forName("BIG5")`, but not class `class BIG5 {}`

**Comment by wangliang181230** [comment]
I have solved this problem: `<buildArg>-H:+AddAllCharsets</buildArg>`
```xml
<plugin>
	<groupId>org.graalvm.buildtools</groupId>
	<artifactId>native-maven-plugin</artifactId>
	<configuration>
		<buildArgs>
			<buildArg>-H:+AddAllCharsets</buildArg>
		</buildArgs>
	</configuration>
</plugin>
```
