### ISSUE TITLE
Does not work with lucene 8.10

### ISSUE THREAD

**Issue by chekanov** [graalvm/native-build-tools#156]
I'm testing a simple Lucene 8.10 search example. I use : 

- java 17.0.1
- graalvm-ce-java17-21.3.0
- Ubuntu 20.4

Jar file works fine when using Java jar. I also can compile my example to the native binary using the command 

```shell
${GRAALVM_HOME}/bin/native-image \
    -cp $CLASSPATH \
    --enable-https --enable-url-protocols --enable-http \
    -H:Name=Example -H:Class=testclass -H:+ReportUnsupportedElementsAtRuntime --allow-incomplete-classpath
```

However, during execution of this binary, I've got this: 

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.ensureInitialized(DynamicHub.java:552)
	at java.lang.Class.ensureInitialized(DynamicHub.java:552)
	at java.lang.Class.ensureInitialized(DynamicHub.java:552)
	at org.apache.lucene.analysis.core.WhitespaceAnalyzer.createComponents(WhitespaceAnalyzer.java:48)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:199)
	at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:259)
	at org.apache.lucene.queryparser.classic.QueryParserBase.newFieldQuery(QueryParserBase.java:473)
	at org.apache.lucene.queryparser.classic.QueryParserBase.getFieldQuery(QueryParserBase.java:465)
	at org.apache.lucene.queryparser.classic.QueryParserBase.handleBareTokenQuery(QueryParserBase.java:828)
	at org.apache.lucene.queryparser.classic.QueryParser.Term(QueryParser.java:469)
	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:355)
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:244)
	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215)
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109)
	at Example.java:177)
Caused by: java.lang.IllegalArgumentException: Cannot lookup accessible no-arg constructor for: org.apache.lucene.analysis.tokenattributes.PackedTokenAttributeImpl
	at org.apache.lucene.util.AttributeFactory.findAttributeImplCtor(AttributeFactory.java:48)
	at org.apache.lucene.util.AttributeFactory.getStaticImplementation(AttributeFactory.java:143)
	at org.apache.lucene.analysis.TokenStream.<clinit>(TokenStream.java:86)
	... 16 more
Caused by: java.lang.NoSuchMethodException: no such constructor: org.apache.lucene.analysis.tokenattributes.PackedTokenAttributeImpl.<init>()void/newInvokeSpecial
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:974)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
	at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2750)
	at org.apache.lucene.util.AttributeFactory.findAttributeImplCtor(AttributeFactory.java:46)
	... 18 more
Caused by: java.lang.NoSuchMethodError: org.apache.lucene.analysis.tokenattributes.PackedTokenAttributeImpl.<init>()
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:342)
	at java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:239)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
	... 21 more
```

Apparently Lucene code used in searches:

       
```java
QueryParser parser = new QueryParser("title", analyser);
Query query = parser.parse( SEARCH );
```

failed when compiling with  graalvm . Any ideas?

**Comment by lazar-mitrovic** [comment]
This issue isn't related to `native-build-tools` since you are invoking `native-image` by hand.

You should create new issue at https://github.com/oracle/graal/issues/, but first make sure that you have generated necessary configuration using [native-image-agent](https://www.graalvm.org/reference-manual/native-image/Agent/), and built an image using said configuration.
