### ISSUE TITLE
Resources detection fails if a classpath entry is missing

### ISSUE THREAD

**Issue by melix** [graalvm/native-build-tools#175]
If the classpath contains an element, say `build/resources/test` and that this element doesn't exist, then the build would fail with:

```
Caused by: java.nio.file.NoSuchFileException: build/resources/test
        at org.graalvm.buildtools.model.resources.ClassPathDirectoryAnalyzer.initialize(ClassPathDirectoryAnalyzer.java:66)
        at org.graalvm.buildtools.model.resources.ClassPathEntryAnalyzer.getResources(ClassPathEntryAnalyzer.java:66)
        at org.graalvm.buildtools.gradle.tasks.GenerateResourcesConfigFile.detectResourcesFromClasspathEntry(GenerateResourcesConfigFile.java:136)
        at org.graalvm.buildtools.gradle.tasks.GenerateResourcesConfigFile.detectResourcesFromClasspath(GenerateResourcesConfigFile.java:117)
        at org.graalvm.buildtools.gradle.tasks.GenerateResourcesConfigFile.generate(GenerateResourcesConfigFile.java:98)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

We should be lenient and ignore missing entries.

**Comment by melix** [comment]
Something is adding `build/resources/test` to the classpath although the directory doesn't exist. We should probably avoid that, but the native plugin could be lenient with missing resources: https://github.com/graalvm/native-build-tools/issues/175
