### ISSUE TITLE
nativeCompile results always in Error: Main entry point class 'com.xxx.Application' not found.

### ISSUE THREAD

**Issue by matus-gazo** [graalvm/native-build-tools#213]
Hello all,

I am running into a weird problem with the plugin (v0.9.10) where it always ends up with an error about not able to find the Main entry point class. Funnily enough I am able to do a build with Paketo/ gradle bootBuildImage just fine and I also do see the *.jar with class in the -imagecp classpath and also in the generated args file, so not sure what's wrong. 

Any ideas please? 
Much appreciated, thank you.

========================================================================================================================
GraalVM Native Image: Generating 'service-mock'...
========================================================================================================================
[1/7] Initializing...                                                                                   (15.3s @ 1.79GB)
Error: Main entry point class 'com.xxx.Application' not found.
com.oracle.svm.core.util.UserError$UserException: Main entry point class 'com.xxx.Application' not found.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:367)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:587)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:126)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:617)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1770)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1477)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1438)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1425)

**build.gradle file:**
....

bootBuildImage {
    builder = "paketobuildpacks/builder:tiny"
    environment = [
            "BP_NATIVE_IMAGE": "true",
            "BP_JVM_VERSION" : "17.*"
    ]
}

springAot {
    mode = AotMode.NATIVE
    debugVerify = false
    removeXmlSupport = true
    removeJmxSupport = true
    removeYamlSupport = true
    verify = true
    debugVerify = true
    mainClass = 'com.xxx.Application'
    applicationClass = 'com.xxx.Application'
}

graalvmNative {
    binaries {
        main {
            verbose = true
            fallback = true
            buildArgs.add('-H:+ReportExceptionStackTraces')
        }
    }
}

**Comment by davecramer** [comment]
I have the same issue, even though I can copy the exact arguments and run it manually and it works
```
$JAVA_HOME/bin/native-image -cp /Users/davecra/projects/jdbcbench/build/libs/nativecompile-classpath-0.1-SNAPSHOT.jar --no-fallback --verbose -H:Path=/Users/davecra/projects/jdbcbench/build/native/nativeCompile -H:Name=jdbcbench -H:ConfigurationFileDirectories=/Users/davecra/projects/jdbcbench/build/native/generated/generateResourcesConfigFile -H:Class=rocks.postgres.JDBCBench -H:+ReportExceptionStackTraces
```

However `gradlew nativeCompile' fails with `Error: Main entry point class '@/var/folders/nx/ghf_9dtj429390tmrybbf7w80000gr/T/native-image16394532788938476208args' not found.`

**Comment by davecramer** [comment]
@melix thx, that worked!

**Comment by lazar-mitrovic** [comment]
@matus-gazo Would you mind testing with the latest release (0.9.12)?

**Comment by matus-gazo** [comment]
> @matus-gazo Would you mind testing with the latest release (0.9.12)?

Unfortunately still the same error...

**Comment by lazar-mitrovic** [comment]
Hey @matus-gazo,
Are you able to share some kind of a reproducer (or at least `verbose` level log)? 
Without seeing the `native-image` invocation I doubt that anyone would be able to debug this issue.

**Comment by linghengqian** [comment]
- I know this issue is tagged with `gradle-plugin`, but I also see this issue with `maven-plugin`. I built https://github.com/linghengqian/test-graalvm-nbt as a test, the relevant log is output via Github Actions, refer to https://github.com/linghengqian/test-graalvm-nbt/actions/runs/3117484101/jobs/5056174887 .

- I hope the strange shape of this repository won't bother too many people, because I took it out and tested it from https://github.com/apache/shardingsphere/pull/21109.
```
Error: Main entry point class 'org.apache.shardingsphere.proxy.Bootstrap' neither found on the classpath nor on the modulepath.
classpath: '/home/runner/work/shardingsphere/shardingsphere'
modulepath: '/opt/hostedtoolcache/graalvm-ce-java17-linux/22.2.0/x64/graalvm-ce-java17-22.2.0/lib/svm/library-support.jar'
com.oracle.svm.core.util.UserError$UserException: Main entry point class 'org.apache.shardingsphere.proxy.Bootstrap' neither found on the classpath nor on the modulepath.
classpath: '/home/runner/work/shardingsphere/shardingsphere'
modulepath: '/opt/hostedtoolcache/graalvm-ce-java17-linux/22.2.0/x64/graalvm-ce-java17-22.2.0/lib/svm/library-support.jar'
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:72)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:348)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1716)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1413)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1374)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1361)
```

**Comment by dagnelies** [comment]
Same error here.

```
Error: Main entry point class 'com.elo.datafill.DatafillApplication' neither found on the classpath nor on the modulepath.
classpath: 'C:\elo-workspace\datafill\target\datafill-0.0.1.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\boot\spring-boot-starter-tomcat\3.0.2\spring-boot-starter-tomcat-3.0.2.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\spring-context\6.0.4\spring-context-6.0.4.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\spring-core\6.0.4\spring-core-6.0.4.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\boot\spring-boot-devtools\3.0.2\spring-boot-devtools-3.0.2.jar;C:\Users\Dagnelies\.m2\repository\ch\qos\logback\logback-core\1.4.5\logback-core-1.4.5.jar;C:\Users\Dagnelies\.m2\repository\com\squareup\okio\okio-jvm\3.0.0\okio-jvm-3.0.0.jar;C:\Users\Dagnelies\.m2\repository\jakarta\annotation\jakarta.annotation-api\2.1.1\jakarta.annotation-api-2.1.1.jar;C:\Users\Dagnelies\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.14.1\jackson-annotations-2.14.1.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\spring-beans\6.0.4\spring-beans-6.0.4.jar;C:\Users\Dagnelies\.m2\repository\io\micrometer\micrometer-observation\1.10.3\micrometer-observation-1.10.3.jar;C:\Users\Dagnelies\.m2\repository\io\micrometer\micrometer-commons\1.10.3\micrometer-commons-1.10.3.jar;C:\Users\Dagnelies\.m2\repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.14.1\jackson-module-parameter-names-2.14.1.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\spring-web\6.0.4\spring-web-6.0.4.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\spring-webmvc\6.0.4\spring-webmvc-6.0.4.jar;C:\Users\Dagnelies\.m2\repository\org\json\json\20220924\json-20220924.jar;C:\Users\Dagnelies\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk8\1.7.22\kotlin-stdlib-jdk8-1.7.22.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\boot\spring-boot-starter-web\3.0.2\spring-boot-starter-web-3.0.2.jar;C:\Users\Dagnelies\.m2\repository\ch\qos\logback\logback-classic\1.4.5\logback-classic-1.4.5.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\spring-jcl\6.0.4\spring-jcl-6.0.4.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\boot\spring-boot-autoconfigure\3.0.2\spring-boot-autoconfigure-3.0.2.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\boot\spring-boot-starter-json\3.0.2\spring-boot-starter-json-3.0.2.jar;C:\Users\Dagnelies\.m2\repository\com\google\code\gson\gson\2.9.1\gson-2.9.1.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\boot\spring-boot-starter-logging\3.0.2\spring-boot-starter-logging-3.0.2.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\spring-aop\6.0.4\spring-aop-6.0.4.jar;C:\Users\Dagnelies\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.14.1\jackson-datatype-jsr310-2.14.1.jar;C:\Users\Dagnelies\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.14.1\jackson-core-2.14.1.jar;C:\Users\Dagnelies\.m2\repository\org\apache\logging\log4j\log4j-api\2.19.0\log4j-api-2.19.0.jar;C:\Users\Dagnelies\.m2\repository\org\apache\tomcat\embed\tomcat-embed-websocket\10.1.5\tomcat-embed-websocket-10.1.5.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\spring-expression\6.0.4\spring-expression-6.0.4.jar;C:\Users\Dagnelies\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk7\1.7.22\kotlin-stdlib-jdk7-1.7.22.jar;C:\Users\Dagnelies\.m2\repository\com\auth0\java-jwt\4.2.2\java-jwt-4.2.2.jar;C:\Users\Dagnelies\.m2\repository\org\apache\logging\log4j\log4j-to-slf4j\2.19.0\log4j-to-slf4j-2.19.0.jar;C:\Users\Dagnelies\.m2\repository\com\meilisearch\sdk\meilisearch-java\0.9.0\meilisearch-java-0.9.0.jar;C:\Users\Dagnelies\.m2\repository\org\apache\tomcat\embed\tomcat-embed-el\10.1.5\tomcat-embed-el-10.1.5.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\boot\spring-boot-starter\3.0.2\spring-boot-starter-3.0.2.jar;C:\Users\Dagnelies\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.7.22\kotlin-stdlib-common-1.7.22.jar;C:\Users\Dagnelies\.m2\repository\org\slf4j\jul-to-slf4j\2.0.6\jul-to-slf4j-2.0.6.jar;C:\Users\Dagnelies\.m2\repository\org\yaml\snakeyaml\1.33\snakeyaml-1.33.jar;C:\Users\Dagnelies\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.14.1\jackson-databind-2.14.1.jar;C:\Users\Dagnelies\.m2\repository\com\squareup\okhttp3\okhttp\4.10.0\okhttp-4.10.0.jar;C:\Users\Dagnelies\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.14.1\jackson-datatype-jdk8-2.14.1.jar;C:\Users\Dagnelies\.m2\repository\org\springframework\boot\spring-boot\3.0.2\spring-boot-3.0.2.jar;C:\Users\Dagnelies\.m2\repository\org\slf4j\slf4j-api\2.0.6\slf4j-api-2.0.6.jar;C:\Users\Dagnelies\.m2\repository\org\apache\tomcat\embed\tomcat-embed-core\10.1.5\tomcat-embed-core-10.1.5.jar;C:\Users\Dagnelies\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.7.22\kotlin-stdlib-1.7.22.jar;C:\Users\Dagnelies\.m2\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar'
modulepath: 'C:\tools\graalvm-ce-java17-22.3.1\lib\svm\library-support.jar'
```

**Comment by matus-gazo** [comment]
Hi, I did not manage to make this work on Spring Boot 2x. 
With ugprade to Spring Boot 3 and 'org.graalvm.buildtools.native' version '0.9.20' AND some manual tweaking of jar/bootJar tasks it finally works now. Without this manual config it would either not compile and/or run for me:

`
jar {
    enabled = true
    archiveClassifier = 'plain'
    from file("$buildDir/generated/aotClasses")
    from sourceSets.aot.output
    from collectReachabilityMetadata
}

bootJar {
    enabled = true
    from file("$buildDir/generated/aotClasses")
    from sourceSets.main.output
    from sourceSets.aot.output
    from collectReachabilityMetadata
    duplicatesStrategy = DuplicatesStrategy.WARN
}`

 I think ideally the gradle plugin should work out of the box...

For reference, this is my graalVmNative section:

`
graalvmNative {
    toolchainDetection = false
    testSupport = false
    agent {
        enabled = false
    }
    metadataRepository {
        enabled = true
    }
    binaries {
        main {
            mainClass = 'com.blazemeter.mock.ServiceMockApplication'
            sharedLibrary = false
            debug = false // Determines if debug info should be generated, defaults to false (alternatively add --debug-native to the CLI)
            verbose = true // Add verbose output, defaults to false
            fallback = false // Sets the fallback mode of native-image, defaults to false
            quickBuild = false // Determines if image is being built in quick build mode (alternatively use GRAALVM_QUICK_BUILD environment variable, or add --native-quick-build to the CLI)
            richOutput = true // Determines if native-image building should be done with rich output
            buildArgs.addAll(['--install-exit-handlers', '--enable-all-security-services', '--enable-http', '--enable-https'])
        }
    }
}
`

**Comment by gotson** [comment]
I have a [similar problem](https://github.com/spring-projects/spring-boot/issues/36397), my project is open-source and available [here](https://github.com/gotson/komga/tree/native) if any of the maintainers want to try and reproduce.

**Comment by jvukicev** [comment]
Closing because this thread now covers multiple distinct main-class/classpath scenarios, and there is no single reproducible plugin issue to act on. One reported cause is disabling the plain JAR with `jar { enabled = false }`; remove that configuration if present. If the problem persists, please open a new issue with a minimal reproducer, the complete native-image invocation, and the relevant plugin, Gradle/Maven, Java, GraalVM, and Spring versions.
