### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: No application context available after calling main method of 'com.fss.aeps.Application'. Does it run a SpringApplication?

### ISSUE THREAD

**Issue by KrishnaST** [graalvm/native-build-tools#319]
Error on native build for a Jakarta EE Spring Boot application.

```
Exception in thread "main" java.lang.IllegalStateException: No application context available after calling main method of 'com.fss.aeps.Application'. Does it run a SpringApplication?
	at org.springframework.boot.AotProcessor$AotProcessorHook.run(AotProcessor.java:232)
	at org.springframework.boot.AotProcessor.process(AotProcessor.java:103)
	at org.springframework.boot.AotProcessor.main(AotProcessor.java:198)
```

[log.txt](https://github.com/graalvm/native-build-tools/files/9667527/log.txt)

[pom.txt](https://github.com/graalvm/native-build-tools/files/9667536/pom.txt)

<img width="668" alt="image" src="https://user-images.githubusercontent.com/9427954/192849404-dc6181ea-8ddf-4cb0-856f-f460183d63fe.png">

**Comment by cwweng** [comment]
Removing the try catch solved the problem in my case.

**Comment by melix** [comment]
Closing as non relevant to this project (relates to Spring).
