### ISSUE TITLE
reflect-config.json file not listing classes loaded dynamically via Javascript execution

### ISSUE THREAD

**Issue by mkubec** [graalvm/native-build-tools#361]
**Describe the bug**
Configuration file reflect-config.json generated by executing java with 
```
-agentlib:native-image-agent=config-output-dir=<dir>
```
doesn't contain java classes dynamically loaded by Javascript.

**To Reproduce**
Compile following code:
```
public class PrintUUID1 {
    public static void main(String[] args)  {
        try (Context context = Context.newBuilder("js")
                .engine(Engine.create())
                .allowHostClassLookup(s -> true)
                .allowHostAccess(HostAccess.ALL)
                .allowIO(true)
                .build()) {
            context.eval("js", "print('Hello from JavaScript!');");
            context.eval("js", "const UUID = Java.type('java.util.UUID');" +
                                    "print(UUID.randomUUID().toString());");
        }
    }
}
```

Run:
```
java -agentlib:native-image-agent=config-output-dir=./graalvm_configs PrintUUID1 
```
reflect-config.json contains just following classes:
```
[
  {"name":"java.security.MessageDigestSpi"},
  {"name":"java.security.SecureRandomParameters"},
  {"name":"org.graalvm.polyglot.Engine", "methods":[{"name":"getImpl","parameterTypes":[] }]},
  {"name":"org.graalvm.polyglot.management.Management"},
  {"name":"sun.security.provider.NativePRNG", "methods":[{"name":"<init>","parameterTypes":[] }]},
  {"name":"sun.security.provider.SHA", "methods":[{"name":"<init>","parameterTypes":[] }]}
]
```
It's missing Java class loaded by Javascript via Java.type() - class UUID and methods randomUUID() and toString().

**Expected behavior**
Reflection config file should probably contain also classes loaded from Javascript via Java.type() call.

**System Info (please complete the following information):**
 - OS: `Mac`
 - GraalVM Version:
```
java version "11.0.17" 2022-10-18 LTS
Java(TM) SE Runtime Environment GraalVM EE 22.3.0 (build 11.0.17+10-LTS-jvmci-22.3-b07)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.0 (build 11.0.17+10-LTS-jvmci-22.3-b07, mixed mode)
```
The same happens with version:
```
java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment GraalVM EE 22.3.0 (build 17.0.5+9-LTS-jvmci-22.3-b07)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.0 (build 17.0.5+9-LTS-jvmci-22.3-b07, mixed mode, sharing)
```

**Additional context**
Native image created with generated reflect-config.json produces following error:
```
Exception in thread "main" TypeError: Access to host class java.util.UUID is not allowed or does not exist.
        at <js> :program(Unnamed:1:13-39)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:425)
        at PrintUUID.main(PrintUUID.java:23)
```
It requires to manually add missing class and methods.

**Comment by melix** [comment]
Closing as this is unrelated to the Maven or Gradle build plugins, which this repository is about. Note that I have verified that the behavior with the plugin is the same, so it's an issue with the agent (/cc @gradinac ).
