### ISSUE TITLE
org.apache.maven.plugin.MojoExecutionException on mac

### ISSUE THREAD

**Issue by ancientelves** [graalvm/native-build-tools#382]
**Describe the bug**
when i execute 'mvn package -Pnative' on mac,occur the below error:
GraalVM Native Image: Generating 'graalvm-sample' (executable)...
[1/7] Initializing...
Error: Error compiling query code (in /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c). Compiler command '/usr/bin/cc -Wall -Werror -Wno-tautological-compare -ObjC -o /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c' output included error: /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c:31:10: fatal error: 'Foundation/Foundation.h' file not found
    C file contents around line 31:
    /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c:30: #include <unistd.h>
    /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c:31: #include <Foundation/Foundation.h>
    /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c:32: #include <mach/mach.h>
com.oracle.svm.core.util.UserError$UserException: Error compiling query code (in /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c). Compiler command '/usr/bin/cc -Wall -Werror -Wno-tautological-compare -ObjC -o /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c' output included error: /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c:31:10: fatal error: 'Foundation/Foundation.h' file not found
    C file contents around line 31:
    /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c:30: #include <unistd.h>
    /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c:31: #include <Foundation/Foundation.h>
    /var/folders/ml/_m7mq6kn4mxfh26888yq5dz40000gn/T/SVM-17490525441314111332/PosixDirectives.c:32: #include <mach/mach.h>
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:139)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:371)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1715)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1121)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:915)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)

**System Info (please complete the following information):**
 - OS: mac
 - GraalVM Version :
 openjdk version "17.0.5" 2022-10-18 LTS
OpenJDK Runtime Environment GraalVM 22.3.0 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM GraalVM 22.3.0 (build 17.0.5+8-LTS, mixed mode, sharing)
 - Java Version [e.g. `17`]
 - Plugin version [e.g. `native-gradle-plugin:0.9.10`]

<profiles>
		<profile>
			<id>native</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<version>0.9.19</version>
						<extensions>true</extensions>
						<executions>
							<execution>
								<id>build-native</id>
								<goals>
									<goal>compile-no-fork</goal>
								</goals>
								<phase>package</phase>
							</execution>
							<execution>
								<id>test-native</id>
								<goals>
									<goal>test</goal>
								</goals>
								<phase>test</phase>
							</execution>
						</executions>
						<configuration>
							<mainClass>${exec.mainClass}</mainClass>
							<buildArgs>
								<buildArg>--verbose</buildArg>
								<buildArg>-H:+ReportExceptionStackTraces</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

**Comment by jvukicev** [comment]
Hello ancientelves,

Apologies for the very late response to this issue. As the issue contains no reproducer and uses very outdated `GraalVM` and `native-build-tools` versions (that were actual at the time, but that is no longer the case), I'll go ahead and close it as `non-reproducible`.

If you still have this issue with new versions of Graal and NBT, feel free to reopen the issue with steps on how to reproduce the issue on the current configurations.
