### ISSUE TITLE
 Preview features are not enabled for AsyncConfiguration (class file version 63.65535). Try running with '--enable-preview'

### ISSUE THREAD

**Issue by pruidong** [graalvm/native-build-tools#383]
Using the GraalVM Maven plug-in, I was prompted to turn on the preview feature when generating a local image (Spring Boot 3 application).

environment:

Windows 10
java -version:

openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08, mixed mode, sharing)

Exception message:

```
Caused by: java.lang.UnsupportedClassVersionError: Preview features are not enabled for com/test/config/AsyncConfiguration (class file version 63.65535). Try running with '--enable-preview'
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:495)
        at java.base/java.lang.Class.forName(Class.java:474)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:283)
        at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:461)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1569)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1502)
        ... 16 common frames omitted
```

pom.xml

```xml

<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

<build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.json</include>
                    <include>**/*.xml</include>
                    <include>**/*.yml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>
                        -agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/
                    </jvmArguments>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>19</release>
                    <compilerArgs>
                        <arg>--enable-preview</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <configuration>
                    <buildArgs>
                        <buildArg>--enable-preview</buildArg>
                    </buildArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

What should I do about it? thank you

**Comment by jvukicev** [comment]
Thanks for the report, and sorry this stayed unanswered for so long.

This command runs the application on the JVM via the Spring Boot Maven plugin:

```bash
mvn -Pnative spring-boot:run
```

The `--enable-preview` option therefore also has to be passed to that JVM invocation. The `native-maven-plugin` `<buildArgs>` configuration only applies when `native-image` is invoked; it does not affect `spring-boot:run`.

In your example, the Spring Boot plugin already has `jvmArguments`, so it should include both options, for example:

```xml
<jvmArguments>
  --enable-preview -agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/
</jvmArguments>
```

Since this is a configuration issue rather than a Native Build Tools bug, I am closing this issue. If you still see a problem after passing `--enable-preview` to the JVM running `spring-boot:run`, please let us know and we can reopen.
