### ISSUE TITLE
executable works only with @EnableWebMvc annotation in spring boot's config

### ISSUE THREAD

**Issue by arthures11** [graalvm/native-build-tools#389]
exactly the title, without this while trying to run the executable i will always get the errors like this:
```
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceHandlerMapping': Instantiation of supplied bean failed
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1236) ~[workdayapp.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[workdayapp.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[workdayapp.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[workdayapp.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[workdayapp.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[workdayapp.exe:6.0.4]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[workdayapp.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[workdayapp.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[workdayapp.exe:6.0.4]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[workdayapp.exe:6.0.4]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[workdayapp.exe:6.0.4]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[workdayapp.exe:6.0.4]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[workdayapp.exe:3.0.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[workdayapp.exe:3.0.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[workdayapp.exe:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[workdayapp.exe:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[workdayapp.exe:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[workdayapp.exe:3.0.2]
```

**Comment by bclozel** [comment]
This needs to be [reported against Spring Boot](https://github.com/spring-projects/spring-boot/issues) as this plugin is not involved here. Please create a new Spring Boot issue with a sample project reproducing the problem. Thanks!
