### ISSUE TITLE
`-H:+PrintImageObjectTree` -> Fatal error: `java.lang.NullPointerException`: Cannot invoke "`com.oracle.svm.hosted.meta.HostedMetaAccess.lookupJavaField(java.lang.reflect.Field)`" because "`this.hMetaAccess`" is null

### ISSUE THREAD

**Issue by wangliang181230** [graalvm/native-build-tools#402]
When I added the option `-H:+PrintImageObjectTree`, the following error was reported:

```log
Fatal error: java.lang.NullPointerException: Cannot invoke "com.oracle.svm.hosted.meta.HostedMetaAccess.lookupJavaField(java.lang.reflect.Field)" because "this.hMetaAccess" is null
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionFeature.getDeletionReason(ReflectionFeature.java:292)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.target.Target_java_lang_reflect_Field$FieldDeletionReasonComputer.transform(Target_java_lang_reflect_Field.java:169)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.computeValue(ComputedValueField.java:343)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:313)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:38)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:97)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:79)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:158)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:365)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.ObjectScanner.finish(ObjectScanner.java:389)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:114)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ObjectTreePrinter.doPrint(ObjectTreePrinter.java:77)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ObjectTreePrinter.lambda$print$0(ObjectTreePrinter.java:65)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.reportImpl(ReportUtils.java:154)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:90)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:72)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:68)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ObjectTreePrinter.print(ObjectTreePrinter.java:64)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.AnalysisReporter.printAnalysisReports(AnalysisReporter.java:52)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:788)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Error: Image build request failed with exit status 1
```

**Comment by wangliang181230** [comment]
https://github.com/oracle/graal/issues/6218
