### ISSUE TITLE
InetAddress.getAllByName("baidu.com") run exception

### ISSUE THREAD

**Issue by wghdir** [graalvm/native-build-tools#416]
source code:
    public String getHostAddress() {
        InetAddress ia;
        try {
            InetAddress inetAddress[] = InetAddress.getAllByName("baidu.com");
            for (int i = 0; i < inetAddress.length; i++) {
                System.out.println("+++++++++address++++++++++++++"+inetAddress[i].getHostAddress());
            }
        } catch (UnknownHostException e) {
            System.out.println("++++++++++++++run error++++++++++++++++++++");
            e.printStackTrace();
            System.out.println("++++++++++++++run error++++++++++++++++++++");
        }
        return "127.0.0.1";
    }

error msg:
java.net.UnknownHostException: baidu.com: System error
        at java.base@17.0.6/java.net.Inet4AddressImpl.lookupAllHostAddr(Inet4AddressImpl.java)
        at java.base@17.0.6/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
        at java.base@17.0.6/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1534)
        at java.base@17.0.6/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base@17.0.6/java.net.InetAddress.getAllByName0(InetAddress.java:1524)
        at java.base@17.0.6/java.net.InetAddress.getAllByName(InetAddress.java:1381)
        at java.base@17.0.6/java.net.InetAddress.getAllByName(InetAddress.java:1305)
        at com.example.demo.RunAfterBoot.getPropertyValue(RunAfterBoot.java:24)
        at com.example.demo.RunAfterBoot.run(RunAfterBoot.java:19)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
        at com.example.demo.DemoApplication.main(DemoApplication.java:13)
I was run in Alpine.why display this error msg.i use native-image with --static

**Comment by melix** [comment]
Please read the issue templates, this isn't related to the build plugins.
