### ISSUE TITLE
generateResourceConfig not working

### ISSUE THREAD

**Issue by blackstar-baba** [graalvm/native-build-tools#441]
**Describe the bug**
I am clone this demo https://github.com/graalvm/native-build-tools/tree/master/samples/java-application-with-resources and change some plugin versions,  when i am running the result after build native image,  throw npe like this:
```
***** native-with-resource % ./target/example-app 
Exception in thread "main" java.lang.NullPointerException
        at java.base@17.0.5/java.io.Reader.<init>(Reader.java:168)
        at java.base@17.0.5/java.io.InputStreamReader.<init>(InputStreamReader.java:76)
        at org.graalvm.demo.Application.getMessages(Application.java:11)
        at org.graalvm.demo.Application.main(Application.java:16)
```

**To Reproduce**

my source code: https://github.com/blackstar-baba/native-with-resource

run this command: `mvn -Pnative clean package`

**System Info (please complete the following information):**
 - OS: [`MACOS AMD64`]
 - GraalVM Version [`22.0 CE`]
 - Java Version [`17`]
 - Plugin version [`native-gradle-plugin:0.9.22`]

**Additional context**

**Comment by blackstar-baba** [comment]
additional context:
`target/native/generated/generatedResourceConfig/resource-config.json` includes is empty, like this:
```
{
  "resources" : {
    "includes" : [ ],
    "excludes" : [ ]
  },
  "bundles" : [ ]
}
```

**Comment by blackstar-baba** [comment]
I looked this test case: JavaApplicationWithResourcesFunctionalTest and i used this command: `mvn -Pnative  -DskipTests -Dresources.autodetection.enabled=true clean package` which can working. I think we need some docs for how to use this.

**Comment by blackstar-baba** [comment]
I think we can set  property `resources.autodetection.enabled` equals `true` default.

**Comment by melix** [comment]
The Gradle plugin also uses `false` as a default value, which I think is a _safe_ default, especially because if you start using the agent in combination, you can easily get duplicate resources (both defined in what we infer and what is found by the agent). So I'd stick with `false`.

**Comment by blackstar-baba** [comment]
How about update this demo: `java-application-with-resources` ?  it can't working now.

**Comment by blackstar-baba** [comment]
It can working if add codes in `pom.xml` properties like this: 
```
 <resources.autodetection.enabled>true</resources.autodetection.enabled>
```

**Comment by melix** [comment]
Well, the sample does what it's expected to do, in the sense that it's used in tests to check the behavior when this or that flag is not enabled. It's a sample app which contains resources, and which needs to be tested against different scenarios: `resources.autodetection.enabled=true`, or the agent, etc...

You could argue that the name `samples` is not very well chosen in this case, since it's _test projects_ which are also used in samples.

**Comment by blackstar-baba** [comment]
Can we add `readme.md` file in demo project to tell users add properties?

**Comment by melix** [comment]
But what would you say in that readme? To use the property or to use the agent? We have a guides for both the Maven and Gradle plugins which explain precisely this. If we add a README to the samples, IMO it should be to tell to look at the guides instead.

**Comment by blackstar-baba** [comment]
Is this the guides: https://graalvm.github.io/native-build-tools/latest/index.html ? i can't find descriptions about property `resources.autodetection.enabled`, that's why I'm here.

**Comment by jvukicev** [comment]
Sorry for the late reply.

This is expected behavior. `generateResourceConfig` writes the legacy Native Image `resource-config.json` file. For Maven, resource autodetection is disabled by default, so the generated file can be empty unless resources are configured explicitly or autodetection is enabled.

For this sample, you can enable autodetection with:

    mvn -Pnative -Dresources.autodetection.enabled=true clean package

We intentionally keep autodetection disabled by default because it can include more resources than expected or duplicate metadata provided by existing config/the tracing agent.

Also note that `generateResourceConfig` is mainly a compatibility path for producing legacy `resource-config.json` metadata. New metadata should generally use `reachability-metadata.json` where possible, but `resource-config.json` remains supported for existing projects.

For that reason, I am closing this issue, but feel free to reopen with more details if this still blocks your use case.
