### ISSUE TITLE
How to load dynamic class in springboot native model

### ISSUE THREAD

**Issue by wghdir** [graalvm/native-build-tools#473]
**I want to load dynamic class in springboot native model,but i get a error.**
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:92)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130)
at java.base@17.0.7/java.lang.ClassLoader.defineClass(ClassLoader.java:288)
at zcsoft.nativex.util.MyClassLoader.findClass(MyClassLoader.java:43)
at zcsoft.nativex.util.MyClassLoader.exportClass(MyClassLoader.java:78)
at zcsoft.nativex.util.UtilApplication.main(UtilApplication.java:18)
**How to load dynamic class in native model,I don't know how to generate predefined-classes-config.json.**
The DynamicLoad.class need copy to /data/classes from demo resource
[nativex-dynamic.zip](https://github.com/graalvm/native-build-tools/files/12178623/nativex-dynamic.zip)

**Comment by wghdir** [comment]
It doesn't feel very useful, you need  have the hashcode of the class, you can't import arbitrary classes
