### ISSUE TITLE
Backslash in native-image-xxx.args is removed on Windows and build fails

### ISSUE THREAD

**Issue by Dacesilian** [graalvm/native-build-tools#507]
I'm using Maven plugin with ```mvn clean package -Dnative```, build ends with error `Execution of native-image.cmd returned non-zero result`. It's because args file is generated with backslashes and they're being ignored, as is seen below. I've also noticed that there is `t` missing from target folder name, it's probably because of interpreting it as `\t (tab character)`

```
--- native:0.9.26:compile-no-fork (build-native)
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <   > at index 38: C:devmyappanotherfolder   argetapp-5.1.2-SNAPSHOT.jar
        at java.base@20.0.2/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base@20.0.2/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base@20.0.2/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base@20.0.2/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base@20.0.2/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base@20.0.2/java.nio.file.Path.of(Path.java:148)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.expandAsteriskClassPathElement(NativeImage.java:1795)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1774)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:435)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:72)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1703)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:223)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1703)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:2016)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:945)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1592)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1557)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1531)
```

**To Reproduce**

```mvn clean package -Dnative```

I'm using this Maven configuration:
```<plugin>
                    <groupId>org.graalvm.buildtools</groupId>
                    <artifactId>native-maven-plugin</artifactId>
                    <version>${native-build-tools-plugin.version}</version>
                    <extensions>true</extensions>
                    <executions>
                        <execution>
                            <id>add-reachability-metadata</id>
                            <goals>
                                <goal>add-reachability-metadata</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>build-native</id>
                            <goals>
                                <goal>compile-no-fork</goal>
                            </goals>
                            <phase>package</phase>
                        </execution>
                    </executions>
                    <configuration>
                        <imageName>${project.artifactId}</imageName>
                        <mainClass>${start-class}</mainClass>
                        <verbose>true</verbose>
                        <debug>true</debug>
                        <useArgFile>true</useArgFile>
                        <metadataRepository>
                            <enabled>true</enabled>
                        </metadataRepository>
                        <buildArgs>
                            <buildArg>-H:TempDirectory=${project.build.directory}/tmp</buildArg>
                        </buildArgs>
                    </configuration>
                </plugin>
```

**Expected behavior**
When I replace backslashes with forward slashes, it's working fine:
`C:\Program Files\Java\graalvm-jdk-20.0.2+9.1\bin\native-image.cmd @target\tmp\native-image-11363221642868185872.args my.start.AppClass`

**System Info (please complete the following information):**
 - OS: `Windows 11 22621.2283`
 - GraalVM Version `graalvm-jdk-20.0.2+9.1`
 - Java Version `20`
 - Plugin version `native-maven-plugin:0.9.26`

Thank you.

**Comment by chirontt** [comment]
FYI: a new version of `native-maven-plugin`, 0.9.27, has been uploaded to Maven Central, which fixes this problem in Windows.

**Comment by olpaw** [comment]
@chirontt thanks for answering. @Dacesilian please reopen if you can still reproduce the issue with the latest version.

**Comment by csx-bill** [comment]
> 仅供参考：新版本的 0.9.27 已上传到 Maven Central，它修复了 Windows 中的此问题。`native-maven-plugin`
Windows11 

最新版本重现该问题
The latest version reproduces the issue
jdk: graalvm-jdk-21  
native-maven-plugin： 0.9.28
Execution of C:\Program Files\Java\graalvm-jdk-21\bin\native-image.cmd @target\tmp\native-image-9279884616099713869.args returned non-zero result

**Comment by zhaommmmomo** [comment]
@chirontt @olpaw 
I encountered a similar problem in version 0.10.2

target\tmp\native-image-1456193413344267072.args returned non-zero result


jdk：graalvm-jdk-17
native-maven-plugin：0.10.2
native-image:properties:
```
Args=--initialize-at-build-time=cn.zmm.graalvmtest.GraalvmTestApplication
```

**Comment by chirontt** [comment]
@zhaommmmomo I have no problem with [graalvm-jdk-17.0.9](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-17.0.9) and same native-maven-plugin version as yours, for compiling my project on a Windows box.
