### ISSUE TITLE
Graalvm cannot find the functional interface writeReplace method

### ISSUE THREAD

**Issue by veione** [graalvm/native-build-tools#508]
### code：
```java
@GetMapping("test")
    public String test() throws Exception {
        MyFunc<Student, String> myFunc = Student::studentName;
        String name = getName(myFunc);
        return name;
    }

    public <T> String getName(Serializable func) throws Exception {
        Method[] methods = func.getClass().getDeclaredMethods();
        for (Method method : methods) {
            log.info("method:::::::::::::: {}", method.getName());
        }
        Method method = func.getClass().getDeclaredMethod("writeReplace");
        method.setAccessible(true);
        SerializedLambda lambda = (SerializedLambda) method.invoke(func);
        return lambda.getImplMethodName();
    }
```

### runtime environment：
- graalvm-ce-java17-22.3.3
- idea
- window 11

### error report：
2023-09-16T23:23:36.530+08:00 ERROR 23848 --- [nio-9090-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NoSuchMethodException: com.think.HelloController$$Lambda$8087d8810b3a19322654a88f59bbaf9acc2cf42b.writeReplace()] with root cause

java.lang.NoSuchMethodException: com.think.HelloController$$Lambda$8087d8810b3a19322654a88f59bbaf9acc2cf42b.writeReplace()
        at java.base@17.0.8/java.lang.Class.getDeclaredMethod(DynamicHub.java:2675) ~[springboot-graalvm-demo.exe:na]
        at com.think.HelloController.getName(HelloController.java:52) ~[springboot-graalvm-demo.exe:na]
        at com.think.HelloController.test(HelloController.java:33) ~[springboot-graalvm-demo.exe:na]
        at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568) ~[springboot-graalvm-demo.exe:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[springboot-graalvm-demo.exe:6.0.7]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:537) ~[springboot-graalvm-demo.exe:6.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[springboot-graalvm-demo.exe:6.0.7]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:631) ~[springboot-graalvm-demo.exe:6.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[springboot-graalvm-demo.exe:10.1.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[springboot-graalvm-demo.exe:6.0.7]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[na:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[na:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[springboot-graalvm-demo.exe:10.1.7]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[na:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[springboot-graalvm-demo.exe:10.1.7]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[na:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[na:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[na:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[springboot-graalvm-demo.exe:10.1.7]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[na:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[na:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[springboot-graalvm-demo.exe:10.1.7]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[na:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[na:na]
        at java.base@17.0.8/java.lang.Thread.run(Thread.java:833) ~[springboot-graalvm-demo.exe:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[springboot-graalvm-demo.exe:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178) ~[na:na]

Looking forward to receiving a response as soon as possible.

**Comment by fniephaus** [comment]
This issue seems unrelated to native build tools, could you please open a new one at https://github.com/oracle/graal/issues? Please add a complete reproducer, so that we can help you fix the problem. Thanks!
