### ISSUE TITLE
(Gradle) Running tests with agent fails with "Missing property userCodeFilterPath in agent conditional configuration"

### ISSUE THREAD

**Issue by abelsromero** [graalvm/native-build-tools#554]
**Describe the bug**
Running `./gradlew -Pagent nativeTest` as per [documentation](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#agent-support) in a project with no configuration (except adding the plugin), fails with

```
Caused by: org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of property 'agentOptions'.
        at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:248)
        at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:239)
        at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:135)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:105)
        at org.gradle.api.internal.provider.ProviderResolutionStrategy$1.resolve(ProviderResolutionStrategy.java:27)
        at org.gradle.util.internal.DeferredUtil.unpack(DeferredUtil.java:59)
        at org.gradle.util.internal.DeferredUtil.unpackOrNull(DeferredUtil.java:49)
        at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:38)
        at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:30)
        ... 72 more
Caused by: org.gradle.api.GradleException: Missing property userCodeFilterPath in agent conditional configuration
        at org.graalvm.buildtools.gradle.internal.agent.AgentConfigurationFactory.lambda$getAgentConfiguration$653f1fdd$1(AgentConfigurationFactory.java:81)
        at org.gradle.api.internal.provider.ValueSupplier$Present.transform(ValueSupplier.java:541)
        at org.gradle.api.internal.provider.TransformBackedProvider.mapValue(TransformBackedProvider.java:91)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:83)

```

env:
* Gradle: 8.5 (latest)
* 'org.graalvm.buildtools.native' version '0.9.28' (latest)
* GraalVM: 21.0.1 CE (latest)
* Reproducer: branch, https://github.com/abelsromero/java-parallels/tree/add-native-java-compatibility

**Make sure that you have read [the documentation](https://graalvm.github.io/native-build-tools) and that you are using the latest plugin version.**

**To Reproduce**

```
git clone -b add-native-java-compatibility git@github.com:abelsromero/java-parallels.git
cd java-parallels
./gradlew -Pagent nativeTest
```

**Expected behavior**
It should run tests and provide auto-generated metadata 🙏 

**Logs**

**System Info (please complete the following information):**
 - OS: MacOs
 - GraalVM Version: 21.0.1 CE
 - Java Version: 21
 - Plugin version: 'org.graalvm.buildtools.native' version '0.9.28'

**Additional context**

**Comment by abelsromero** [comment]
Looking at the code, it seems the issue is that it's setting the "conditional" mode by default. Forcing the `standard` works `./gradlew -Pagent=standard nativeTest`.
But base on other [docs](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#agent-support), it seems `standard` should be the default.

**Comment by sdelamo** [comment]
I hit this issue today as well. @abelsromero workaround of using `-Pagent=standard` worked

**Comment by melix** [comment]
Alright so I'm moving this to a documentation issue.
