### ISSUE TITLE
Sporadic Gradle failure:  access-filter.json already exists

### ISSUE THREAD

**Issue by jeanbisutti** [graalvm/native-build-tools#626]
The Native Build Tools Gradle plugin is used in the [OpenTelemetry Java instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation) Github repository. 

Sometimes the plugin fails. A failure report example: https://ge.opentelemetry.io/s/2rq2vt7d7bsng/failure?expanded-stacktrace=WyIwLTEtMi0zLTQiXQ#1

The root case:

```
Caused by: java.nio.file.FileAlreadyExistsException: /tmp/agent-config
at org.graalvm.buildtools.agent.AgentConfiguration.addDefaultAccessFilter(AgentConfiguration.java:156)	
at org.graalvm.buildtools.agent.AgentConfiguration.getAgentCommandLine(AgentConfiguration.java:99)	
at org.gradle.api.internal.provider.ValueSupplier$Present.transform(ValueSupplier.java:519) 
```

The problem seems to come from the recent changes in the [AgentConfiguration](https://github.com/graalvm/native-build-tools/blob/c4305294bdf3519a2db2af1916c85689a3842467/common/utils/src/main/java/org/graalvm/buildtools/agent/AgentConfiguration.java#L55) class, and released in 0.10.3.

The native agent is not enabled from our [build.gradle.kts](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/f0c25aecd006262929668f04d836309e3b3b071b/smoke-tests-otel-starter/spring-boot-reactive-3/build.gradle.kts#L62) file or a command line (`./gradlew -Pagent`). Perhaps some code related to the agent could only be executed if the agent is enabled.

Would you have any workaround to recommend?

Thanks.

**Comment by dnestoro** [comment]
Please use `0.10.2` version util we fix the problem. Thanks for reporting!

**Comment by ghilainm** [comment]
I have the same kind of issue with the version 0.10.4. The processAot tasks is run in the context of a multi project Gradle build wih parallel feature enabled. It seems to be not supported. Can you confirm @dnestoro ?

```
Caused by: org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of property 'agentOptions'.
	at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:[284](https://gitlab.arhs-developments.com/BPC/acceptorpsp/acceptor-psp-transaction-engine/-/jobs/4750122#L284))
	at org.gradle.api.internal.provider.AbstractProperty.lambda$beforeRead$0(AbstractProperty.java:276)
	at org.gradle.api.internal.provider.ValueState.finalizeOnReadIfNeeded(ValueState.java:139)
	at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:276)
	at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:268)
	at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:162)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:105)
	at org.gradle.api.internal.provider.ProviderResolutionStrategy$1.resolve(ProviderResolutionStrategy.java:27)
	at org.gradle.util.internal.DeferredUtil.unpack(DeferredUtil.java:59)
	at org.gradle.util.internal.DeferredUtil.unpackOrNull(DeferredUtil.java:49)
	at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:38)
	at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:30)
	... 98 more
Caused by: java.lang.RuntimeException: Cannot add default access-filter.json
	at org.graalvm.buildtools.agent.AgentConfiguration.addDefaultAccessFilter(AgentConfiguration.java:180)
	at org.graalvm.buildtools.agent.AgentConfiguration.getAgentCommandLine(AgentConfiguration.java:101)
	at org.gradle.api.internal.provider.ValueSupplier$Present.transform(ValueSupplier.java:519)
	at org.gradle.api.internal.provider.TransformBackedProvider.mapValue(TransformBackedProvider.java:91)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:82)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
	at org.gradle.api.internal.provider.Collectors$ElementsFromCollectionProvider.collectEntries(Collectors.java:280)
	at org.gradle.api.internal.provider.AbstractCollectionProperty$CollectingSupplier.calculateValue(AbstractCollectionProperty.java:500)
	at org.gradle.api.internal.provider.AbstractCollectionProperty.finalValue(AbstractCollectionProperty.java:311)
	at org.gradle.api.internal.provider.AbstractCollectionProperty.finalValue(AbstractCollectionProperty.java:79)
	at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:281)
	... 109 more
Caused by: java.nio.file.FileAlreadyExistsException: /tmp/agent-config/access-filter_71_173383205[296](https://gitlab.arhs-developments.com/BPC/acceptorpsp/acceptor-psp-transaction-engine/-/jobs/4750122#L296)2_.json
	at org.graalvm.buildtools.agent.AgentConfiguration.addDefaultAccessFilter(AgentConfiguration.java:169)
	... 119 more
```

**Comment by ghilainm** [comment]
It seems task are really run in // at the same millisecond :).

```
            long pid = ProcessHandle.current().pid();
            long time = System.currentTimeMillis();
            Path tmpAccessFilter = agentDir.resolve(ACCESS_FILTER_PREFIX + '_' + pid  + '_' + time  + '_' + ACCESS_FILTER_SUFFIX);
            Files.copy(accessFilterData, tmpAccessFilter);
```

**Comment by dnestoro** [comment]
> It seems task are really run in // at the same millisecond :).

Can you please replace milliseconds with nanoseconds in the current implementation and run your tests again to see if the problem still occurs?

**Comment by dnestoro** [comment]
Hey @jeanbisutti @ghilainm I recently merged a fix for this issue. Can you try if it resolves the problem on your projects? 

Since it is already on master, you can build the plugin locally ([see this](https://github.com/graalvm/native-build-tools/blob/master/native-gradle-plugin/README.md)) and apply locally built plugin to your project.

**Comment by jeanbisutti** [comment]
@dnestoro I have not reproduced the issue locally. The issue was only observed in a CI. Do you have the possibility to publish a snapshot?

**Comment by ghilainm** [comment]
@dnestoro Sorry have no time to test that. Can't easily reproduce sporadic issue. But I will upgrade to next version and check if the issue still happens.

**Comment by dnestoro** [comment]
@ghilainm thanks! I hope next version (`0.10.5`) will be released in the incoming weeks

**Comment by dnestoro** [comment]
@jeanbisutti @ghilainm can you please check if the error still occurs with the latest (`0.10.5`) release?

I will close this ticket. Feel free to reopen it if you experience the same failure with the new Native Build Tools version
